### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by joepb** [tmackness/dropbox-ignore-node_modules#1]
Totally out of curiosity: Why would you want your codebase to reside on Dropbox? 
Especially with it's bi-directional synchronization, that's disaster waiting to happen, isn't it?

**Comment by tmackness** [comment]
I mean it is possible to have issues if you work on the same thing at the same time or if the file hasn’t been synced and you work with the file on another device. But dropbox it good at dealing with conflicts. 

But that hasn’t been an issue for me as I don’t use Dropbox as a replacement for Git. I store everything on my computer in the cloud including my coding projects. 

I find it helps when moving between computers or saving changes that have not yet been committed/pushed. I never lose anything I do. Ever. 

The only down side until now was the pesky node_modules which hogged resources for no reason. So with this it fixes that. I realise there would be a lot of syncing taking place but honestly you never notice it nor is it an issue. I’ve been doing this for years. I wouldn’t recommend using dropbox for working on codebase as a team. It’s more for personal benefits. Use in conjunction with Git. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
