### ISSUE TITLE
It doesn't work on Windows10 64-bit powershell

### ISSUE THREAD

**Issue by hodory** [tmackness/dropbox-ignore-node_modules#2]
Hi, thanks for share nice repo.

I ran it on Windows10, but it doesn't work with Exception. 

I will attach the capture images.

![image](https://user-images.githubusercontent.com/25384187/79231838-a158b080-7ea1-11ea-8528-7850cba7b211.png)

Thanks.

**Comment by tmackness** [comment]
Please now test. merged PR
