### ISSUE TITLE
Failure with path that has many spaces

### ISSUE THREAD

**Issue by ronnycbo** [tmackness/dropbox-ignore-node_modules#4]
I'm using MacOS, the path has many spaces, but the script only corrects 1 space, for the correction of all, I suggest changing the function:

.replace(" ", "\\ ")

to

.replace(/ /g, "\\ ")

**Comment by creativewax** [comment]
had the same issue, this sorts it out when there is multiple spaces across different folder

.replace(/\s+/g, '\\ ')

**Comment by tmackness** [comment]
I have now updated this
